### ISSUE TITLE
Is this the new Readium web project ?

### ISSUE THREAD

**Issue by mbret** [readium/divina-player-js#12]
Sorry if the question has already been asked but is this project the new reader replacing readium web v1 ?

**Comment by llemeurfr** [comment]
Hi, not exactly. The new Readium Web project is started in readium/web (monorepo). 

Divina is a format specific to comics, manga, webtoons ... incubated in EDRLab + Readium Foundation.  

This Divina player has already been integrated in [Thorium Reader](https://www.edrlab.org/software/thorium-reader/).
It will soon be also integrated in [Readium Mobile](https://readium.org/development/projects).
And it will later be integrated in Readium Web as a specialized Navigator.
