### ISSUE TITLE
Apple Retina display: 25% lower-right corner of canvas viewport renders image, the rest is black

### ISSUE THREAD

**Issue by danielweck** [readium/divina-player-js#6]
If I launch the webview on external full HD monitor (non-Retina), then the canvas renders fine at 100% coverage of visible viewport, and I can then move the browser window to my Retina display fine (i.e. 100% viewport).
So it seems the problem occurs when starting the canvas on Retina.

https://github.com/pixijs/pixi.js/issues?q=is%3Aissue+retina

**Comment by danielweck** [comment]
<img width="912" alt="Screenshot 2020-07-25 at 12 49 04" src="https://user-images.githubusercontent.com/625201/88457157-2299e900-ce7c-11ea-8f4f-2c82239d2ad6.png">

**Comment by danielweck** [comment]
<img width="912" alt="Screenshot 2020-07-23 at 19 21 13" src="https://user-images.githubusercontent.com/625201/88457201-612fa380-ce7c-11ea-8e62-10261c8f5b45.png">

**Comment by anymus** [comment]
Issue corrected in commit 93c4532
